# Generated by Django 2.1.4 on 2018-12-04 13:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration', models.FloatField(choices=[(-2, 'Nieusprawiedliwiony występ'), (-1, 'Nieusprawiedliwione'), (0, 'Nie będzie'), (0.75, 'Spóźni się'), (1, 'Będzie)')], default=1)),
                ('comment', models.CharField(max_length=255)),
                ('date_of_declaration', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField(null=True)),
                ('place', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255, null=True)),
                ('scores', models.FileField(null=True, upload_to='')),
                ('yt_link', models.TextField()),
                ('voices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('soprano1', 'soprano1'), ('soprano2', 'soprano2'), ('soprano3', 'soprano3'), ('soprano4', 'soprano4'), ('alto1', 'alto1'), ('alto2', 'alto2'), ('alto3', 'alto3'), ('alto4', 'alto4'), ('tenor1', 'tenor1'), ('tenor2', 'tenor2'), ('tenor3', 'tenor3'), ('tenor4', 'tenor4'), ('bas1', 'bas1'), ('bas2', 'bas2'), ('bas3', 'bas3'), ('bas4', 'bas4')], max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.CharField(choices=[('soprano1', 'soprano1'), ('soprano2', 'soprano2'), ('soprano3', 'soprano3'), ('soprano4', 'soprano4'), ('alto1', 'alto1'), ('alto2', 'alto2'), ('alto3', 'alto3'), ('alto4', 'alto4'), ('tenor1', 'tenor1'), ('tenor2', 'tenor2'), ('tenor3', 'tenor3'), ('tenor4', 'tenor4'), ('bas1', 'bas1'), ('bas2', 'bas2'), ('bas3', 'bas3'), ('bas4', 'bas4')], max_length=255)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='songs',
            field=models.ManyToManyField(to='attendance.Song'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
