# Generated by Django 2.1.4 on 2018-12-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20181204_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='songs',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='declaration',
            field=models.FloatField(choices=[(-2, 'nieusprawiedliwiony występ'), (-1, 'nieusprawiedliwione'), (0, 'nie będzie'), (0.75, 'spóźni się'), (1, 'będzie')], default=1),
        ),
        migrations.AddField(
            model_name='eventsongs',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Event'),
        ),
        migrations.AddField(
            model_name='eventsongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Song'),
        ),
        migrations.AddField(
            model_name='event',
            name='songs_list',
            field=models.ManyToManyField(through='attendance.EventSongs', to='attendance.Song'),
        ),
    ]
